# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown

# Site settings
baseurl: "/zeppelin-grunt"
url: "http://gdg-x.github.io"
permalink: '/blog/:title'

# Varibles
googleAnalyticsTrackingId: "UA-43643469-5"
webtoolsSiteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"
disqusShortName: "devfestua"